config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact', as: :contact
  post 'contact', to: 'contacts#create'
  get 'field', to: 'pages#field'
  get 'detail1', to: 'pages#detail1'
  get 'detail2', to: 'pages#detail2'
  get 'detail3', to: 'pages#detail3'
  get 'detail4', to: 'pages#detail4'
  get 'detail5', to: 'pages#detail5'
  get 'detail6', to: 'pages#detail6'
  get 'detail7', to: 'pages#detail7'
  get 'detail8', to: 'pages#detail8'
  get 'detail9', to: 'pages#detail9'
  get 'detail10', to: 'pages#detail10'

  get '404', to: 'errors#not_found'
  get '500', to: 'errors#internal_server'
  get '422', to: 'errors#unprocessable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/page.rb
class Page < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # def address
  #   [street, city, state, country].compact.join(',')
  # end
  # def google_map(center)
  #   "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=500x500&zoom=17&key=#{Rails.application.credentials.MAPS_API_KEY}"
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    contact = contact_params
    Rails.logger.info "Contact form submitted: #{contact.inspect}"

    # Send email
    ContactMailer.new_contact(contact).deliver_now

    flash[:notice] = "Mesajınız gönderildi — teşekkürler!"
    redirect_to contact_path
  end

  private

  def contact_params
    params.require(:contact).permit(:name, :phone, :email, :message)
  end


end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController

  def not_found
    render status: 404
  end

  def internal_server
    render status: 500
  end

  def unprocessable
    render status: 422
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home; end
  def about; end

  def contact; end

  def field; end

  def detail1; end
  def detail2; end
  def detail3; end
  def detail4; end
  def detail5; end
  def detail6; end
  def detail7; end
  def detail8; end
  def detail9; end
  def detail10; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Avukat Murat Erakın</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag "favicon-96x96.png", rel: "icon", type: "image/png" %>
    <link rel="shortcut icon" href="/assets/images/favicon/favicon.ico" />
  </head>

  <body>
    <% unless controller_name == "errors" %>
      <%= render "shared/navbar" %>
    <% end %>
    <main>
      <% flash.each do |type, message| %>
        <div class="flash-message" style="
            position: fixed;
            top: 60px;
            left: 50%;
            transform: translateX(-50%);
            z-index: 1050;
            background: <%= type == 'notice' ? '#d4edda' : '#f8d7da' %>;
            color: <%= type == 'notice' ? '#155724' : '#721c24' %>;
            padding: 15px 30px;
            border-radius: 5px;
            box-shadow: 0 2px 6px rgba(0,0,0,0.2);
            transition: transform 0.5s ease, opacity 0.5s ease;
            ">
          <%= message %>
        </div>
      <% end %>
      <%= yield %>
    </main>
    <% unless controller_name == "errors" %>
      <%= render "shared/footer" %>
    <% end %>
    <script>
      console.log("%cHey there, curious developer! 👋\nThis awesome website was crafted by Ayse Gungormez – https://github.com/aysegun", "color: #555555; font-weight: bold; font-size: 12px;");

       // Flash auto-hide after 5 seconds
      document.addEventListener("DOMContentLoaded", () => {
        const flashes = document.querySelectorAll(".flash-message");
        flashes.forEach(flash => {
          setTimeout(() => {
            flash.style.opacity = "0";
            flash.style.transform = "translateX(-50%) translateY(-20px)"; // slide up
            setTimeout(() => flash.remove(), 500); // remove after animation
          }, 3000); // 3 seconds
        });
      });
    </script>
  </body>
</html>

app/views/pages/_marker.html.erb
<%= image_tag "Main_Logo.png", height: 30, width: 30, alt: "Logo" %>

app/views/pages/about.html.erb
<div class ="banner" style="background-image: url(<%= asset_path 'books.jpg' %>);">
  <div class ="banner-container d-none d-md-block d-lg-block">
      <h1>Hakkımızda</h1>
  </div>
</div>

<div class="card-container">
  <div class="card border border-0">
    <div class="card-image">
      <%= image_tag "dragon.jpg", :alt => "murat erakin", width:280, height:420 %>
    </div>
    <div class="card-info mb-3">
      <p>Av. Murat Erakın</p>
    </div>
  </div>

  <div class="about-card">
    <div class ="container">
      <div class ="row">
        <div class ="col-lg-6">
          <p style="font-weight: bold">Av. Murat Erakın</p>
        </div>
        <div class ="col-lg-6">
          <p style="font-weight: bold">İletişim</p>
          <p class= "mb-0"></p>
          <p><%= mail_to "info@muraterakin.av.tr" %></p>
        </div>
      </div>
      <p style="margin-top:10px">
        Erakın Hukuk Bürosu, 2018 yılında kurulmuş olup, Av Murat Erakın'ın gayrimenkul sektöründe
        uzun yıllara dayanan tecrübesiyle temelleri atılmıştır. Kuruluşundan bu yana, hukukun farklı alanlarında birey ve kurumlara
        güvenilir, etkili ve çözüm odaklı hizmetler sunmayı ilke edinmiştir.
        Büromuz, müvekkillerine yalnızca yasal süreçlerde rehberlik etmekle kalmaz,
        aynı zamanda stratejik danışmanlık anlayışıyla kalıcı çözümler üretir.
        Uzmanlık alanlarımız geniş bir yelpazeye yayılmakta olup, hem yerel hem de uluslararası düzeyde
        hukuki destek sağlanmaktadır.
      </p>
      <p>
        Büromuz; Ceza Hukuku, Gayrimenkul Hukuku, Borçlar Hukuku, İcra ve İflas Hukuku,
        Medeni Hukuk, Şirketler Hukuku alanlarında uzmanlaşmış olup 2018 yılından
        itibaren İstanbul'da faaliyetlerine devam etmektedir.
      </p>
      <%= link_to "< Ana Sayfa", root_path %>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class ="banner" style="background-image: url(<%= asset_path 'bnwcolumns.jpg'  %>);">
  <div class ="banner-container d-none d-md-block d-lg-block">
      <h1>İletişim</h1>
  </div>
</div>

<div class="contact-container">
  <!-- Contact Info Card -->
  <div class="contact-card">
    <div class = "container">
      <div class="contact-info row">
        <h3>İstanbul Ofis | Merkez Ofis</h3>
        <div class="phone col-lg-12 mt-5" style="visibility: hidden;">
          <p style="font-weight: bold;color:white" class = "col-lg-3">Telefon:</p>
          <%= link_to "+905335180850", class:"col-lg-9"%>
        </div>
        <div class="address">
          <p style="font-weight: bold" class = "col-lg-3">Adres:</p>
          <p class ="col-lg-9">İzzetpaşa Mah, Yeni Yol Cad, <br> No:3 Kat:3 Ofis No:3<br> Nurol Tower, Şişli/İstanbul</p>
        </div>
      </div>
      <p style="color:#e60d0d; margin-top:20px">Formu doldurarak bizimle iletişime geçebilirsiniz.</p>
    </div>
  </div>
  <!-- Contact Form Card -->
  <div class="contact-card">
    <div class="container">
      <div class="contact-form-info">
        <h3>İletişim Formu</h3>
        <%= form_with url: contact_path, method: :post, scope: :contact, local: true, data: { turbo: false } do |f| %>
          <div class="row">
            <div class="col-lg-6">
              <%= f.label :name, "Ad-Soyad *" %>
              <%= f.text_field :name, class: "form-control", required: true %>
            </div>
            <div class="col-lg-6">
              <%= f.label :phone, "Telefon *" %>
              <%= f.telephone_field :phone, class: "form-control", required: true %>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-lg-12">
              <%= f.label :email, "Email address *" %>
              <%= f.email_field :email, class: "form-control", required: true %>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-lg-12">
              <%= f.label :message, "Mesajınız *" %>
              <%= f.text_area :message, rows: 5, class: "form-control", required: true %>
            </div>
          </div>
          <div class="row mt-3">
            <div class="col-lg-12">
              <%= f.submit "Send", class: "btn btn-dark w-100" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="map">
  <iframe
    src="https://www.google.com/maps/embed?pb=!1m17!1m12!1m3!1d8507.837090487476!2d28.979266270723876!3d41.069546764203075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m2!1m1!2zNDHCsDA0JzAzLjkiTiAyOMKwNTknMDkuOCJF!5e0!3m2!1str!2ses!4v1757600604627!5m2!1str!2ses"
    class="map-iframe"
    allowfullscreen=""
    loading="lazy"
    referrerpolicy="no-referrer-when-downgrade">
  </iframe>
</div>

app/views/pages/detail1.html.erb
<div class ="banner" style="background-image: url(<%= asset_path 'columns.jpg'  %>);">
  <div class ="banner-container d-none d-md-block d-lg-block">
    <p>Ceza Hukuku</p>
  </div>
</div>
<div class="field-detail">
<div class="container">
    <div class ="row">
      <div class="col-lg-4">
        <p style="color:red; font-weight:bold">Çalışma Alanlarımız</p>
        <p class="area"><%= link_to "İcra İflas Hukuku", detail3_path %></p>
        <p class="area"><%= link_to "Gayrimenkul Hukuku", detail6_path %></p>
        <p class="area"><%= link_to "Şirketler Hukuku ve Kurumsal Yönetim", detail7_path %></p>
        <p class="area"><%= link_to "Uluslararası Ticaret Hukuku", detail9_path %></p>
        <p class="area"><%= link_to "Aile Hukuku", detail2_path %></p>
        <p class="area"><%= link_to "Yabancılar ve Vatandaşlık Hukuku", detail4_path %></p>
        <p style="color:rgb(134,134,134)">Ceza Hukuku</p>

        <div class="area-detail d-block d-lg-none">
          <p style="font-weight:bold">Erakın Hukuk Bürosu tarafından Ceza Hukuku alanında verilen hizmetlerden bazıları şunlardır:</p>
          <p class="area-info"><strong>|</strong>Ceza soruşturması ve kovuşturma süreçlerinde hukuki destek sağlanır. </p>
          <p class="area-info"><strong>|</strong>Şüpheli ve sanık haklarının korunmasına yönelik danışmanlık verilir. </p>
          <p class="area-info"><strong>|</strong>Mağdur ve müştekilerin hakları doğrultusunda temsil hizmeti sunulur. </p>
          <p class="area-info"><strong>|</strong>Ceza davalarının takibi ve savunma stratejileri yürütülür. </p>
          <p class="area-info"><strong>|</strong>Adli süreçlerde delil değerlendirmesi ve hukuki raporlama yapılır.</p>
          <p class="area-info"><strong>|</strong>Ceza hukuku ile ilgili mütalaa ve danışmanlık hizmetleri sunulur.</p>
          <p class="area-info"><strong>|</strong>Gözaltı ve tutuklama süreçlerinde danışmanlık sağlanır.</p>
          <p class="area-info"><strong>|</strong>Uzlaşma ve alternatif çözüm yolları konusunda yönlendirme yapılır.</p>
        </div>

        <p class="area"><%= link_to "İş Hukuku", detail5_path %></p>
        <p class="area"><%= link_to "Rekabet Hukuku", detail8_path %></p>
        <p class="area"><%= link_to "Uyuşmazlık Çözümü", detail10_path %></p>
      </div>
      <div class="col-lg-8 d-none d-lg-block">
        <p style="font-weight:bold">Erakın Hukuk Bürosu tarafından Ceza Hukuku alanında verilen hizmetlerden bazıları şunlardır:</p>
        <p class="area-info"><strong>|</strong>Ceza soruşturması ve kovuşturma süreçlerinde hukuki destek sağlanır. </p>
        <p class="area-info"><strong>|</strong>Şüpheli ve sanık haklarının korunmasına yönelik danışmanlık verilir. </p>
        <p class="area-info"><strong>|</strong>Mağdur ve müştekilerin hakları doğrultusunda temsil hizmeti sunulur. </p>
        <p class="area-info"><strong>|</strong>Ceza davalarının takibi ve savunma stratejileri yürütülür. </p>
        <p class="area-info"><strong>|</strong>Adli süreçlerde delil değerlendirmesi ve hukuki raporlama yapılır.</p>
        <p class="area-info"><strong>|</strong>Ceza hukuku ile ilgili mütalaa ve danışmanlık hizmetleri sunulur.</p>
        <p class="area-info"><strong>|</strong>Gözaltı ve tutuklama süreçlerinde danışmanlık sağlanır.</p>
        <p class="area-info"><strong>|</strong>Uzlaşma ve alternatif çözüm yolları konusunda yönlendirme yapılır.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/detail10.html.erb
<div class ="banner" style="background-image: url(<%= asset_path 'columns.jpg'  %>);">
  <div class ="banner-container d-none d-md-block d-lg-block">
    <p>Uyuşmazlık Çözümü</p>
  </div>
</div>
<div class="field-detail">
  <div class="container">
    <div class ="row">
      <div class="col-lg-4">
        <p style="color:red; font-weight:bold">Çalışma Alanlarımız</p>
        <p class="area"><%= link_to "İcra İflas Hukuku", detail3_path %></p>
        <p class="area"><%= link_to "Gayrimenkul Hukuku", detail6_path %></p>
        <p class="area"><%= link_to "Şirketler Hukuku ve Kurumsal Yönetim", detail7_path %></p>
        <p class="area"><%= link_to "Uluslararası Ticaret Hukuku", detail9_path %></p>
        <p class="area"><%= link_to "Aile Hukuku", detail2_path %></p>
        <p class="area"><%= link_to "Yabancılar ve Vatandaşlık Hukuku", detail4_path %></p>
        <p class="area"><%= link_to "Ceza Hukuku", detail1_path %></p>
        <p class="area"><%= link_to "İş Hukuku", detail5_path %></p>
        <p class="area"><%= link_to "Rekabet Hukuku", detail8_path %></p>
        <p style="color:rgb(134,134,134)">Uyuşmazlık Çözümü</p>

        <div class="area-detail d-block d-lg-none">
          <p style="font-weight:bold">Erakın Hukuk Bürosu tarafından Uyuşmazlık Çözümü alanında verilen hizmetlerden bazıları şunlardır:</p>
          <p class="area-info"><strong>|</strong>Hukuki ihtilaflarda dava öncesi strateji belirlenir ve risk analizi yapılır. </p>
          <p class="area-info"><strong>|</strong>Mahkeme nezdinde dava açma ve takibi süreçleri yürütülür. </p>
          <p class="area-info"><strong>|</strong>Arabuluculuk ve tahkim gibi alternatif çözüm yolları uygulanır. </p>
          <p class="area-info"><strong>|</strong>Karşı tarafla uzlaşma görüşmeleri yapılır ve protokoller hazırlanır. </p>
          <p class="area-info"><strong>|</strong>Mahkeme kararlarının icrası ve temyiz başvuruları gerçekleştirilir. </p>
          <p class="area-info"><strong>|</strong>Uyuşmazlıkların hızlı ve etkili çözümü için stratejik hukuki danışmanlık sağlanır.</p>
          <p class="area-info"><strong>|</strong>Taraflar arası anlaşmazlıklarda hukuki haklar korunarak çözüm yolları önerilir.</p>
          <p class="area-info"><strong>|</strong>Ulusal ve uluslararası uyuşmazlıklarda profesyonel temsil ve savunma sunulur.</p>
          <p class="area-info"><strong>|</strong>Hukuki süreç boyunca müvekkillere detaylı bilgilendirme ve rehberlik yapılır.</p>
        </div>

      </div>
      <div class="col-lg-8 d-none d-lg-block">
        <p style="font-weight:bold">Erakın Hukuk Bürosu tarafından Uyuşmazlık Çözümü alanında verilen hizmetlerden bazıları şunlardır:</p>
        <p class="area-info"><strong>|</strong>Hukuki ihtilaflarda dava öncesi strateji belirlenir ve risk analizi yapılır. </p>
        <p class="area-info"><strong>|</strong>Mahkeme nezdinde dava açma ve takibi süreçleri yürütülür. </p>
        <p class="area-info"><strong>|</strong>Arabuluculuk ve tahkim gibi alternatif çözüm yolları uygulanır. </p>
        <p class="area-info"><strong>|</strong>Karşı tarafla uzlaşma görüşmeleri yapılır ve protokoller hazırlanır. </p>
        <p class="area-info"><strong>|</strong>Mahkeme kararlarının icrası ve temyiz başvuruları gerçekleştirilir. </p>
        <p class="area-info"><strong>|</strong>Uyuşmazlıkların hızlı ve etkili çözümü için stratejik hukuki danışmanlık sağlanır.</p>
        <p class="area-info"><strong>|</strong>Taraflar arası anlaşmazlıklarda hukuki haklar korunarak çözüm yolları önerilir.</p>
        <p class="area-info"><strong>|</strong>Ulusal ve uluslararası uyuşmazlıklarda profesyonel temsil ve savunma sunulur.</p>
        <p class="area-info"><strong>|</strong>Hukuki süreç boyunca müvekkillere detaylı bilgilendirme ve rehberlik yapılır.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/detail2.html.erb
<div class ="banner" style="background-image: url(<%= asset_path 'columns.jpg'  %>);">
  <div class ="banner-container d-none d-md-block d-lg-block">
    <p>Aile Hukuku</p>
  </div>
</div>
<div class="field-detail">
  <div class="container">
    <div class ="row">
      <div class="col-lg-4">
        <p style="color:red; font-weight:bold">Çalışma Alanlarımız</p>
        <p class="area"><%= link_to "İcra İflas Hukuku", detail3_path %></p>
        <p class="area"><%= link_to "Gayrimenkul Hukuku", detail6_path %></p>
        <p class="area"><%= link_to "Şirketler Hukuku ve Kurumsal Yönetim", detail7_path %></p>
        <p class="area"><%= link_to "Uluslararası Ticaret Hukuku", detail9_path %></p>
        <p style="color:rgb(134,134,134)">Aile Hukuku</p>

        <div class="area-detail d-block d-lg-none">
          <p style="font-weight:bold">Erakın Hukuk Bürosu tarafından Aile Hukuku alanında verilen hizmetlerden bazıları şunlardır:</p>
          <p class="area-info"><strong>|</strong>Boşanma, nafaka, velayet ve mal paylaşımı davalarında temsil sağlanır. </p>
          <p class="area-info"><strong>|</strong>Evlat edinme ve soybağına ilişkin işlemler yürütülür. </p>
          <p class="area-info"><strong>|</strong>Evlenmeden önce veya sonra mal rejimi sözleşmeleri hazırlanır.</p>
          <p class="area-info"><strong>|</strong>Aile içi şiddet durumlarında koruma kararları alınmasına destek verilir.</p>
          <p class="area-info"><strong>|</strong>Ortak velayet, çocukla kişisel ilişki kurulması gibi konularda danışmanlık sunulur.</p>
          <p class="area-info"><strong>|</strong>Boşanma süreçlerinde müvekkillerin haklarını korumaya yönelik stratejik danışmanlık sağlanır.</p>
          <p class="area-info"><strong>|</strong>Miras, terekeye ilişkin anlaşmazlıklar ve paylaşım süreçlerinde hukuki destek sunulur.</p>
          <p class="area-info"><strong>|</strong>Çocukların yüksek yararı gözetilerek velayet ve ziyaret düzenlemeleri yürütülür.</p>
          <p class="area-info"><strong>|</strong>Aile hukuku ile ilgili sözleşme ve protokoller hazırlanarak yasal güvence sağlanır.</p>
          <p class="area-info"><strong>|</strong>Aile arabuluculuğu ve anlaşmazlıkların dostane çözümü için rehberlik edilir.</p>
        </div>

        <p class="area"><%= link_to "Yabancılar ve Vatandaşlık Hukuku", detail4_path %></p>
        <p class="area"><%= link_to "Ceza Hukuku", detail1_path %></p>
        <p class="area"><%= link_to "İş Hukuku", detail5_path %></p>
        <p class="area"><%= link_to "Rekabet Hukuku", detail8_path %></p>
        <p class="area"><%= link_to "Uyuşmazlık Çözümü", detail10_path %></p>
      </div>
      <div class="col-lg-8 d-none d-lg-block">
        <p style="font-weight:bold">Erakın Hukuk Bürosu tarafından Aile Hukuku alanında verilen hizmetlerden bazıları şunlardır:</p>
        <p class="area-info"><strong>|</strong>Boşanma, nafaka, velayet ve mal paylaşımı davalarında temsil sağlanır. </p>
        <p class="area-info"><strong>|</strong>Evlat edinme ve soybağına ilişkin işlemler yürütülür. </p>
        <p class="area-info"><strong>|</strong>Evlenmeden önce veya sonra mal rejimi sözleşmeleri hazırlanır.</p>
        <p class="area-info"><strong>|</strong>Aile içi şiddet durumlarında koruma kararları alınmasına destek verilir.</p>
        <p class="area-info"><strong>|</strong>Ortak velayet, çocukla kişisel ilişki kurulması gibi konularda danışmanlık sunulur.</p>
        <p class="area-info"><strong>|</strong>Boşanma süreçlerinde müvekkillerin haklarını korumaya yönelik stratejik danışmanlık sağlanır.</p>
        <p class="area-info"><strong>|</strong>Miras, terekeye ilişkin anlaşmazlıklar ve paylaşım süreçlerinde hukuki destek sunulur.</p>
        <p class="area-info"><strong>|</strong>Çocukların yüksek yararı gözetilerek velayet ve ziyaret düzenlemeleri yürütülür.</p>
        <p class="area-info"><strong>|</strong>Aile hukuku ile ilgili sözleşme ve protokoller hazırlanarak yasal güvence sağlanır.</p>
        <p class="area-info"><strong>|</strong>Aile arabuluculuğu ve anlaşmazlıkların dostane çözümü için rehberlik edilir.</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-6">
        <ul class="footer-external">
        <p>DAHA FAZLA BİLGİ</p>
          <li>
            <%= link_to "Hakkımızda", about_path %>
          </li>
          <li>
            <%= link_to "Ana Sayfa", root_path %>
          </li>
          <li>
           <%= link_to "Çalışma Alanlarımız", field_path %>
          </li>
        </ul>
      </div>
      <div class="col-lg-3 col-md-6">
        <ul class="footer-info">
        <p>Bizimle iletişime geçin</p>
          <li class="button">
            <%= button_to contact_path, method: :get, class: "btn btn-outline-info" do %>
              İletişim <i class="fa-solid fa-arrow-right"></i>
            <% end %>
          </li>
        </ul>
      </div>
      <div class="footer-legal">
        <div class="footer-terms">
          © 2025 | All Rights Reserved
        </div>
        <div class="footer-links">
          <a href="https://www.linkedin.com/in/muraterakin/" target='_blank'><i class="fa-brands fa-linkedin"></i></a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-law navbar-expand-sm navbar-dark sticky-top">
  <div class="container-fluid">

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class= "navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Ana Sayfa", root_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Hakkımızda", about_path %>
        </li>
        <li class="nav-item">
          <%= link_to "Çalışma Alanlarımız", field_path %>
        </li>
        <li class="nav-item">
          <%= link_to "İletişim", contact_path %>
        </li>
      </ul>
    </div>
  </div>
</div>


<script>
  document.addEventListener("turbo:load", () => {
    const navEl = document.querySelector('.navbar');

    if (!navEl) return;

    window.addEventListener('scroll', () => {
      if (window.scrollY >= 60) {
        navEl.classList.add('navbar-scroll');
      } else {
        navEl.classList.remove('navbar-scroll');
      }
    });
  });
</script>